CREATE TABLE Buildings (
  OSEBuildingID INT AUTO_INCREMENT PRIMARY KEY,
  PrimaryPropertyType VARCHAR(255),
  BuildingInfo VARCHAR(255),
  BuildingLocation VARCHAR(255)
);

CREATE TABLE Buildings_gfa (
  id INT PRIMARY KEY AUTO_INCREMENT,
  OSEBuildingID INT,
  PropertyUseTypeGFA INT
);

CREATE TABLE Metrics (
  id INT PRIMARY KEY AUTO_INCREMENT,
  OSEBuildingID INT UNIQUE,
  Metric VARCHAR(255),
  Value INT
);

CREATE TABLE Users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  Username VARCHAR(255) UNIQUE,
  Password VARCHAR(255)
);